#!/usr/bin/expect -f
set timeout -1
set t [lindex $argv 0]
set n [lindex $argv 1]
exec "echo 1"
exit 1
spawn ./startchain_main $t $n
match_max 100000
for {set COUNT 0} {$COUNT < $n} {incr COUNT} {
expect "Enter a passphrase to encrypt your key to disk:"
send -- "alicealice\r"
expect "Repeat the passphrase:"
send -- "alicealice\r"
}
expect "Password to sign with 'node0':"
send -- "alicealice\r"
expect eof
 
