#!/bin/bash
user=$1
commonkey=$4
round=0
while true
do
currentround=$(hcli query herb current-round)
while !  hcli tx herb ct-part $commonkey -y --from $user> /dev/null
do
sleep "$(($3/75))"
done 
stage=$(hcli query herb stage)
while [ "$stage" != "stageDSCollecting" ]
do
sleep "$(($3/75))"
stage=$(hcli query herb stage)
done
while !  hcli tx herb decrypt $2 $3 -y --from $user> /dev/null
do
sleep "$(($3/75))"
if [ $(hcli query herb stage) = "stageCtCollecting" ] && [ $(hcli query herb current-round) -eq $(( $currentround + 1 )) ]
then
break
fi
done
while [ $round -ne $(( $currentround + 1 )) ]
do
sleep "$(($3/75))"
round=$(hcli query herb current-round)
done
done

