#!/usr/bin/expect -f
set timeout -1
set t1 [lindex $argv 0]
set t2 [lindex $argv 1]
set n [lindex $argv 2]
spawn ./init_chain_full.sh $t1 $t2 $n
match_max 100000
for {set COUNT 0} {$COUNT < $n} {incr COUNT} {
expect "Enter a passphrase to encrypt your key to disk:"
send -- "alicealice\r"
expect "Repeat the passphrase:"
send -- "alicealice\r"
}
expect "Password to sign with 'client0':"
send -- "alicealice\r"
expect eof
 
